### PR TITLE
Add link to the project of Maya Levy

### PR DESCRIPTION
**Pull request by MayaLevy2**

### CODE REVIEW

**Comment by szabgab** [comment]
The PR is good, but I cannot access https://github.com/MayaLevy2/Pump-Probe-Analysis   is it maybe a "private" repo? (See the settings)

**Comment by MayaLevy2** [comment]
Changed it now.

**Comment by szabgab** [comment]
Excellent. Thanks.

**Comment by szabgab** [comment]
Just one more thing, could you add some sample input files to your repo, please?

**Pull request merged**
